/// Device category dimension shared by session and order facts.
table DimDevice

	column device_id
		dataType: int64
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: device_id

	column device_category
		dataType: string
		summarizeBy: none
		sourceColumn: device_category

	partition DimDevice = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/minhkhoi-data/data-portfolio/main/ecommerce_growth_conversion_power_bi/data/dim_device.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {
				{"device_id", Int64.Type},
				{"device_category", type text}
				})
			in
				Typed
