/// Device category dimension shared by session and order facts.
table DimDevice
	lineageTag: 89ac2ad0-aa85-4757-803d-d1c922c4381a

	column device_id
		dataType: int64
		isHidden
		isKey
		lineageTag: 034d59de-18cd-4ed3-b6eb-3b28b3c1f7ee
		summarizeBy: none
		sourceColumn: device_id

	column device_category
		dataType: string
		lineageTag: c93d4b02-e9f7-4163-8b95-55caefadba63
		summarizeBy: none
		sourceColumn: device_category

	partition DimDevice = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataRoot & "\dim_device.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"device_id", Int64.Type},
					{"device_category", type text}
					})
				in
					Typed

