/// Shared calendar dimension for all three fact tables.
table DimDate
	lineageTag: c988c0f9-61a5-40c6-a74e-1873751e40bf
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: 13ae2216-df9e-4ab3-bdd9-e32ce6c74e43
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: e0dbfdfb-f67e-4912-a76e-e12c6e81a97f
		summarizeBy: none
		sourceColumn: year

	column month_no
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b2cd363e-f92c-4f93-907a-2c70d6130d07
		summarizeBy: none
		sourceColumn: month_no

	column month
		dataType: string
		lineageTag: c59185ba-527d-433f-8744-e8f3a89a3d05
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_no

	column year_month
		dataType: string
		lineageTag: 1f6c0549-9c0b-46ae-bc94-9a64cb19b469
		summarizeBy: none
		sourceColumn: year_month

	column week_start
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: b78fbfe2-6fb5-458c-a47c-f092c74699ba
		summarizeBy: none
		sourceColumn: week_start

		annotation UnderlyingDateTimeDataType = Date

	column day_of_week
		dataType: string
		lineageTag: 0e3a06a7-4321-4d93-b37f-76ba4f3b4bd1
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: day_of_week_no

	column day_of_week_no
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e612515a-45ae-4f47-9050-3474fbb14c33
		summarizeBy: none
		sourceColumn: day_of_week_no

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 89de301b-3fa5-49a5-830b-6316938e1578
		summarizeBy: none
		sourceColumn: is_weekend

	partition DimDate = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataRoot & "\dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"date", type date},
					{"year", Int64.Type},
					{"month_no", Int64.Type},
					{"month", type text},
					{"year_month", type text},
					{"week_start", type date},
					{"day_of_week", type text},
					{"day_of_week_no", Int64.Type},
					{"is_weekend", Int64.Type}
					})
				in
					Typed

