/// Country and regional grouping dimension shared by session and order facts.
table DimGeo

	column geo_id
		dataType: int64
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: geo_id

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column region_group
		dataType: string
		summarizeBy: none
		sourceColumn: region_group

	partition DimGeo = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/minhkhoi-data/data-portfolio/main/ecommerce_growth_conversion_power_bi/data/dim_geo.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {
				{"geo_id", Int64.Type},
				{"country", type text},
				{"region_group", type text}
				})
			in
				Typed
