/// Product catalog attributes used by the order-line fact.
table DimProduct

	column product_key
		dataType: int64
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: product_key

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

	column subcategory
		dataType: string
		summarizeBy: none
		sourceColumn: subcategory

	column base_price
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		sourceColumn: base_price

	partition DimProduct = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/minhkhoi-data/data-portfolio/main/ecommerce_growth_conversion_power_bi/data/dim_product.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {
				{"product_key", Int64.Type},
				{"product_id", type text},
				{"product_name", type text},
				{"category", type text},
				{"subcategory", type text},
				{"base_price", Currency.Type}
				})
			in
				Typed
