/// One row per website session; source columns are hidden in favor of explicit measures.
table FactSessions
	lineageTag: 5dac2609-7313-42cd-83a3-922ad7bc8539

	column session_id
		dataType: string
		isHidden
		lineageTag: 55699aaf-30de-413a-b3dd-d113a1fc286b
		summarizeBy: none
		sourceColumn: session_id

	column user_id
		dataType: string
		isHidden
		lineageTag: a46a4987-5b68-466c-8dcf-d23f694edff1
		summarizeBy: none
		sourceColumn: user_id

	column session_date
		dataType: dateTime
		isHidden
		formatString: yyyy-MM-dd
		lineageTag: 1668d418-fbab-46fa-ada9-a062b25c6d27
		summarizeBy: none
		sourceColumn: session_date

		annotation UnderlyingDateTimeDataType = Date

	column channel_id
		dataType: int64
		isHidden
		lineageTag: be3f9f64-30cb-4f74-860c-686023b0334f
		summarizeBy: none
		sourceColumn: channel_id

	column device_id
		dataType: int64
		isHidden
		lineageTag: 76688406-a610-4ded-8c61-36c45fdda855
		summarizeBy: none
		sourceColumn: device_id

	column geo_id
		dataType: int64
		isHidden
		lineageTag: d0d352f5-6ebe-434f-ac33-8231eaa1d89e
		summarizeBy: none
		sourceColumn: geo_id

	column source
		dataType: string
		isHidden
		lineageTag: 6245a135-d694-4622-b584-ce7fc6d80aac
		summarizeBy: none
		sourceColumn: source

	column medium
		dataType: string
		isHidden
		lineageTag: 6dbfb3e4-f47f-463f-bd08-2442082e3864
		summarizeBy: none
		sourceColumn: medium

	column is_new_user
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0feea41f-1f1c-4030-bfad-c7b5d843ee95
		summarizeBy: none
		sourceColumn: is_new_user

	column engaged_session
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ab4bc84e-75e4-41f2-b8ff-6b177fd38d6f
		summarizeBy: none
		sourceColumn: engaged_session

	column engagement_seconds
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e13b8a0a-4232-4012-bf3c-1fa4fd460325
		summarizeBy: none
		sourceColumn: engagement_seconds

	column pageviews
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f9964915-c2dc-475d-a22a-b9b546fbe199
		summarizeBy: none
		sourceColumn: pageviews

	column view_item
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 15c9a12f-6ad5-443b-82c9-b469805aabe9
		summarizeBy: none
		sourceColumn: view_item

	column add_to_cart
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c01ad753-83fd-46fb-ae62-39632fc94144
		summarizeBy: none
		sourceColumn: add_to_cart

	column begin_checkout
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1fde1ba4-ed3a-4c13-8bfc-bd5e28c7de32
		summarizeBy: none
		sourceColumn: begin_checkout

	column purchase
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5434a333-47cb-454a-9483-3de5b8a94437
		summarizeBy: none
		sourceColumn: purchase

	column order_id
		dataType: string
		isHidden
		lineageTag: 622bb9b2-8065-4d0c-98d3-ab818292c494
		summarizeBy: none
		sourceColumn: order_id

	column session_revenue
		dataType: decimal
		isHidden
		formatString: $#,##0.00
		lineageTag: ece2cbc8-6785-463e-b9c2-422a6a6b63ff
		summarizeBy: none
		sourceColumn: session_revenue

	partition FactSessions = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataRoot & "\fact_sessions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"session_id", type text},
					{"user_id", type text},
					{"session_date", type date},
					{"channel_id", Int64.Type},
					{"device_id", Int64.Type},
					{"geo_id", Int64.Type},
					{"source", type text},
					{"medium", type text},
					{"is_new_user", Int64.Type},
					{"engaged_session", Int64.Type},
					{"engagement_seconds", Int64.Type},
					{"pageviews", Int64.Type},
					{"view_item", Int64.Type},
					{"add_to_cart", Int64.Type},
					{"begin_checkout", Int64.Type},
					{"purchase", Int64.Type},
					{"order_id", type text},
					{"session_revenue", Currency.Type}
					})
				in
					Typed

