/// One row per order line; source columns are hidden in favor of explicit measures.
table FactOrderItems
	lineageTag: aa5ee600-fedd-44de-bbc7-6a0928fd4d32

	column order_id
		dataType: string
		isHidden
		lineageTag: 4ed03bd4-6487-4029-8aef-861da1c12888
		summarizeBy: none
		sourceColumn: order_id

	column session_id
		dataType: string
		isHidden
		lineageTag: 89063149-d1b9-406c-84b1-6802e852db9d
		summarizeBy: none
		sourceColumn: session_id

	column user_id
		dataType: string
		isHidden
		lineageTag: ea444465-dd10-4329-a8f4-1f29cd7ab2b8
		summarizeBy: none
		sourceColumn: user_id

	column order_date
		dataType: dateTime
		isHidden
		formatString: yyyy-MM-dd
		lineageTag: 9a6515ab-50b8-416a-b28b-b01190399299
		summarizeBy: none
		sourceColumn: order_date

		annotation UnderlyingDateTimeDataType = Date

	column product_key
		dataType: int64
		isHidden
		lineageTag: 3531e213-9e4b-4d87-b180-290cee2e2883
		summarizeBy: none
		sourceColumn: product_key

	column channel_id
		dataType: int64
		isHidden
		lineageTag: 81d81d18-ac30-4227-a036-8ebbbd85114c
		summarizeBy: none
		sourceColumn: channel_id

	column device_id
		dataType: int64
		isHidden
		lineageTag: c9de4148-9568-4548-8654-3c0fcb5c64e0
		summarizeBy: none
		sourceColumn: device_id

	column geo_id
		dataType: int64
		isHidden
		lineageTag: 5f04beac-7655-41d4-9c11-46f54f071619
		summarizeBy: none
		sourceColumn: geo_id

	column quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: faad4614-167b-4794-abdf-18d886804117
		summarizeBy: none
		sourceColumn: quantity

	column unit_price
		dataType: decimal
		isHidden
		formatString: $#,##0.00
		lineageTag: 5158639a-1837-431b-bcca-58c5f1566433
		summarizeBy: none
		sourceColumn: unit_price

	column item_revenue
		dataType: decimal
		isHidden
		formatString: $#,##0.00
		lineageTag: caf9d931-7b38-415d-8b0b-b204b67e1941
		summarizeBy: none
		sourceColumn: item_revenue

	partition FactOrderItems = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataRoot & "\fact_order_items.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"order_id", type text},
					{"session_id", type text},
					{"user_id", type text},
					{"order_date", type date},
					{"product_key", Int64.Type},
					{"channel_id", Int64.Type},
					{"device_id", Int64.Type},
					{"geo_id", Int64.Type},
					{"quantity", Int64.Type},
					{"unit_price", Currency.Type},
					{"item_revenue", Currency.Type}
					})
				in
					Typed

