/// One row per completed order; source columns are hidden in favor of explicit measures.
table FactOrders

	column order_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: order_id

	column session_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: session_id

	column user_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: user_id

	column order_date
		dataType: dateTime
		formatString: yyyy-MM-dd
		isHidden
		summarizeBy: none
		sourceColumn: order_date

	column channel_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: channel_id

	column device_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: device_id

	column geo_id
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: geo_id

	column total_quantity
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: total_quantity

	column distinct_products
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: distinct_products

	column total_revenue
		dataType: decimal
		formatString: $#,##0.00
		isHidden
		summarizeBy: none
		sourceColumn: total_revenue

	partition FactOrders = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/minhkhoi-data/data-portfolio/main/ecommerce_growth_conversion_power_bi/data/fact_orders.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {
				{"order_id", type text},
				{"session_id", type text},
				{"user_id", type text},
				{"order_date", type date},
				{"channel_id", Int64.Type},
				{"device_id", Int64.Type},
				{"geo_id", Int64.Type},
				{"total_quantity", Int64.Type},
				{"distinct_products", Int64.Type},
				{"total_revenue", Currency.Type}
				})
			in
				Typed
