table DimDevice
	lineageTag: 6d2051ea-c74f-4251-a1f2-9482912d372a

	column device_id
		dataType: int64
		lineageTag: 001e46db-576d-440d-8a7c-6328deddab40
		summarizeBy: none
		sourceColumn: device_id

	column device_category
		dataType: string
		lineageTag: 126aa224-8c79-4af1-a3a9-78f7bf9c8bb6
		summarizeBy: none
		sourceColumn: device_category

	partition DimDevice = m
		mode: import
		source =
				let
					EmbeddedBase64 = Text.Combine({
						"H4sIAPhNsWoC/0tJLctMTo3PTNFJgbCSE0tS0/OLKrkMdXLzkzJzUrmMgFLF2SX5BVzGOiWJSTmpJVwALsuAbDYAAAA="
					}),
					CompressedBinary = Binary.FromText(EmbeddedBase64, BinaryEncoding.Base64),
					CsvBinary = Binary.Decompress(CompressedBinary, Compression.GZip),
					Source = Csv.Document(CsvBinary, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"device_id", Int64.Type},
					{"device_category", type text}
					})
				in
					Typed

