table DimProduct
	lineageTag: cfe212c2-ff4b-4dc6-8aef-dd59714cdde2

	column product_key
		dataType: int64
		lineageTag: f92c0809-fc37-4659-ab57-23a75274ce6e
		summarizeBy: none
		sourceColumn: product_key

	column product_id
		dataType: string
		lineageTag: 3bd85597-a6e9-422d-be68-0cf9cf62a4d1
		summarizeBy: none
		sourceColumn: product_id

	column product_name
		dataType: string
		lineageTag: 3742fcdb-78d7-4ddd-bb06-992a7b5e78db
		summarizeBy: none
		sourceColumn: product_name

	column category
		dataType: string
		lineageTag: 0ba43531-90c9-4be4-8d26-e5bdc5c93d2d
		summarizeBy: none
		sourceColumn: category

	column subcategory
		dataType: string
		lineageTag: 518e2617-b08b-4631-8034-fb70c0573636
		summarizeBy: none
		sourceColumn: subcategory

	column base_price
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: 53e162c1-1ac4-4fb9-a1c1-cc87bd1911c9
		summarizeBy: none
		sourceColumn: base_price

	partition DimProduct = m
		mode: import
		source =
				let
					EmbeddedBase64 = Text.Combine({
						"H4sIAPhNsWoC/4WV0W7aMBSG7/sUeQBvwnYo5bLQbdUKKxpM03ZTGecAFiGO7GQVe/qd4yQOtKBdcBSb/ye2v9+H0tms1tXLHo6sbJ9NFh8LdQCmVQVb647M1+v4vFYeXkpnNNxwthgMOPti7TaHZJor741OZnZrkxUAuy9L5SBnqw/LnXGVZyL9OB7fCHKJ3mXr7Ip8RHJJcsl+2XpVr1HvQFXWXXHckiMlR8rui8xZkyVz5bWtrhiGZBiSYdit6Lcpk0drM9Prn+sK3Csox4ZhC7dkuI1bcPBagN4nS5RUnn75gjMdk3NEzlHnXIDbWHdQhYbkq9J7uGQcBeMdGe/iK1UZlY+gsiAUgoRjEo7787qolKTkA5RiaX9zafXeR+291uC9dQY842HTnHDziHtlK0gmasvw4xmNGL8LOgLMe8DqUNYelXpf4qeRx9EwbI4TZCytZabKypbXLKNmNUQZS7fPB6defeVMse0X1c8xHpLBiTSPpH9ipl0ysVWFA5Hav+gwxf4VD4A1s21kOQHnEfiyUqbI8Xha73ubDCg40eaR9hScOuAFmdfbEweNeEg6J8ZYui1d0DUHTIixdCCc+gN5sqoP6xzciaObEeGMBdEWkfY3BLa2ds+eNxu8yyyOeVi6INgiwl44OJj6cN0leHAReiH6eBfJEjPdivHYKmMLwCbSrIioi0j9Afw+Waisk9OY8UZJsLG0yrmtPbyXNt2FEIthj8rgtXIoxuScZrr9wrMQDEGAsXQ94/+2QEwQYDHqc1sclcvODN1cICeIsIi3+AmOeodROjPEyWbnxFpE1p+oL+fJ4o2HxnwQuiVRxtJt5LPZ1hgIYDOzAV8dMZtTm+egK7OO8ZYEW0bYc1OY5MdhjW0gVyfGJmhtnCShluJNCBe21rv3loaiJN4y8l4YXeBtmOSqoMbXm7D1ZdZix2wWR+xlZP8d9FHnkIX+c9J7mgBKoi8j/SeT+cuNv10RYcfS3bjretGcLvGWkfcEVHHyL9G312bhBFtG2IsdRp9aR/EmtiGAkjjLcd80kU7y7Lb4gr94hc8MYacpgU7jdZ7Vhd71na8fihC8lAinvD/E2oc3TOvypGHQiId/xJToppHucmfL8qy1Nv0+tIp/ZbndB0oIAAA="
					}),
					CompressedBinary = Binary.FromText(EmbeddedBase64, BinaryEncoding.Base64),
					CsvBinary = Binary.Decompress(CompressedBinary, Compression.GZip),
					Source = Csv.Document(CsvBinary, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Headers, {
					{"product_key", Int64.Type},
					{"product_id", type text},
					{"product_name", type text},
					{"category", type text},
					{"subcategory", type text},
					{"base_price", Currency.Type}
					})
				in
					Typed

